name = "floral-hall-1e2f"
main = "bingx-relay-worker.js"
compatibility_date = "2025-01-01"
keep_vars = true

[[durable_objects.bindings]]
name = "ENGINE"
class_name = "Engine"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Engine"]

